#!/usr/bin/env python3
"""Generate Pokemon/app/src/themes/skins.ts from Pokemon/app/src/themes/scenes.ts.

Embeds each scene's pixel-landscape image (public/scene-*.png/svg) as a
base64 data URL so the Codex desktop skin needs no external assets.

    python3 Pokemon/scripts/generate-skins.py
"""

import base64
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SCENES_TS = REPO / "Pokemon/app/src/themes/scenes.ts"
PUBLIC = REPO / "Pokemon/app/public"
OUT = REPO / "Pokemon/app/src/themes/skins.ts"

SCENE_VARS = ["grassland", "ocean", "cave", "magma", "snowfield", "plant", "space", "city", "lab"]
MIME = {".png": "image/png", ".svg": "image/svg+xml"}


def parse_scenes(ts: str) -> dict[str, dict]:
    scenes: dict[str, dict] = {}
    for block in re.finditer(r"const\s+(\w+):\s*SceneDef\s*=\s*\{(.*?)\n\};", ts, re.S):
        var, body = block.group(1), block.group(2)
        if var not in SCENE_VARS:
            continue
        ui_m = re.search(r"ui:\s*\{(.*?)\n\s*\},", body, re.S)
        img_m = re.search(r"image:\s*'([^']+)'", body)
        if not ui_m or not img_m:
            sys.exit(f"missing ui/image for scene {var}")
        ui = dict(re.findall(r"'?([\w-]+)'?:\s*'(#[0-9A-Fa-f]{6})'", ui_m.group(1)))
        img_rel = img_m.group(1).lstrip("/")
        img_path = PUBLIC / img_rel
        if not img_path.exists():
            sys.exit(f"missing image file {img_path}")
        mime = MIME[img_path.suffix]
        art = f"data:{mime};base64,{base64.b64encode(img_path.read_bytes()).decode()}"
        scenes[var] = {"ui": {k: v.upper() for k, v in ui.items()}, "art": art}
    return scenes


SCENE_META = {
    "grassland": ("草原", "❀", 251),
    "ocean": ("海洋", "≈", 10077),
    "cave": ("洞穴", "◆", 10076),
    "magma": ("岩浆", "▲", 10037),
    "snowfield": ("雪原", "❄", 10193),
    "plant": ("无人发电厂", "⚡", 145),
    "space": ("宇宙", "☄", 10079),
    "city": ("城市", "✦", 151),
    "lab": ("实验室", "⚗", 150),
}


def main() -> None:
    scenes = parse_scenes(SCENES_TS.read_text(encoding="utf-8"))
    missing = set(SCENE_VARS) - set(scenes)
    if missing:
        sys.exit(f"missing scenes: {missing}")

    chunks = [
        "/* AUTO-GENERATED by Pokemon/scripts/generate-skins.py — do not edit. */",
        "/* Scene palettes + base64 wallpapers for the Codex desktop skin (Pokemon/skins/). */",
        "",
        "export interface SkinDef {",
        "  ui: Record<string, string>;",
        "  art: string; // data URL（场景壁纸）",
        "  badgeImg: string; // data URL（招牌 sprite）",
        "  label: string;",
        "}",
        "",
        "export const SKINS: Record<string, SkinDef> = {",
    ]
    for var in SCENE_VARS:
        s = scenes[var]
        name, _sym, mascot_id = SCENE_META[var]
        sprite = PUBLIC / "pokemon" / f"{mascot_id:03d}.png"
        if not sprite.exists():
            sys.exit(f"missing mascot sprite {sprite}")
        badge = f"data:image/png;base64,{base64.b64encode(sprite.read_bytes()).decode()}"
        ui_js = ", ".join(f"'{k}': '{v}'" for k, v in s["ui"].items())
        chunks.append(
            f"  {var}: {{ ui: {{ {ui_js} }}, art: '{s['art']}', badgeImg: '{badge}', label: '{name}' }},"
        )
    chunks.append("};")
    chunks.append("")
    OUT.write_text("\n".join(chunks), encoding="utf-8")
    total_kb = OUT.stat().st_size // 1024
    print(f"wrote {OUT.relative_to(REPO)} ({len(SCENE_VARS)} scenes, {total_kb} KB)")


if __name__ == "__main__":
    main()
